# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title: "NL: The NULL Device"
copyleft: "&copy T. Mueller 2018"

#email: nl@havepowilltravel.com
email: nl@silutions.net

#adminemail: blog-admin@havepowilltravel.com
adminemail: blog-admin@silutions.net

description: >- # this means to ignore newlines until "baseurl:"
  Random thoughts and musings that are being backed up to the NULL device.  Hopefully,
  it will not fill up

#
#  url and baseurl have varients, depending on whether we're in DEVELOPMENT or PRODUCTION.
#
#
# PRODUCTION:
#
baseurl: "/havepowilltravel"
#url: "https://nl.havepowilltravel.com"
url: "https://havepowilltravel.github.io"  # until I register the name


twitter_username: jekyllrb
github_username:  jekyll

header_pages:
  - contact.md
  - cv.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - _site/
